### PR TITLE
Update atree_constants to 2.0.1

### PR DESCRIPTION
**Pull request by FrozenEarth-git**
BIG TODO: uhhh can you handle Enraged Blow cause I have no idea how to, so it's unchanged in this pull

### CODE REVIEW

**Review by ferricles — APPROVED** [review]
lgtm

**Comment by ferricles** [comment]
not sure if master is the right branch, will get back on that

**Comment by FrozenEarth-git** [comment]
Aaaaa some people are saying to only update it to 2.0 hotfix #6 and make a new pr for 2.0.1 

:doom:

**Comment by hppeng-wynn** [comment]
Subsumed / into branch patch_2.0.1 (plus more changes, plus compression)

**Pull request closed without merging**
