### PR TITLE
Replaced credits url

### PR DESCRIPTION
**Pull request by lodenrogue**

### CODE REVIEW

**Comment by hppeng-wynn** [comment]
does this work if you use `../` instead? i'd rather not hardcode it to the site in case someone else deploys it (also we deploy it with a different base URL)

**Comment by lodenrogue** [comment]
Yes ../ works but so does what you had before. "credits.txt"

**Comment by hppeng-wynn** [comment]
i think you do need `../`

oh also realizing this is PR'd off master :blobsweat:

current working branch is `atree`, which has these issues -- i should update that

**Comment by hppeng-wynn** [comment]
let me just merge atree into master for now

**Comment by hppeng-wynn** [comment]
thats probably why everything is working for you locally -- ferricles did a big refactor awhile back that ended up breaking this i think

**Comment by lodenrogue** [comment]
Ok let me take a look at the merged changes

**Comment by hppeng-wynn** [comment]
the "stub files" for crafter/etc have to stay there -- they exist for supporting old links.

the problem files are in `builder/index.html`, `crafter/index.html`...

**Comment by lodenrogue** [comment]
Seems git deleted those files on my end when I merged master into my branch. Should be good now. Take a look

**Review by hppeng-wynn — APPROVED** [review]
lgtm

**Comment by lodenrogue** [comment]
Thanks

**Pull request merged**
